build:
  main: cmd/godol/main.go
  binary: godol
  goos:
  - darwin
  - linux
  - windows
  - freebsd
  - netbsd
  - openbsd
  goarch:
  - amd64
  - 386
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
